version: '3.7'
services:
  backend-rest:
    build: 
      context: ./backend/rest
    volumes: 
      - ./backend/rest:/flask
    environment:
      FLASK_DEBUG: 1
    ports: 
      - 5000:5000
    networks:
      - backend
      - frontend
    command: flask run -p 5000

  backend-streaming:
    build:
      context: ./backend/streaming
    volumes:
      - ./backend/streaming/:/aiohttp
    ports:
      - 5001:5000
    networks:
      - backend
      - frontend
    command: adev runserver -v -p 5000 streaming/app.py    
    
  frontend:
      build:
        context: ./frontend
      volumes: 
        - ./frontend/src:/angular/src
        - ./frontend/package.json:/angular/package.json
        - ./frontend/package-lock.json:/angular/package-lock.json
      command: npm run dev
      ports:
        - 4200:4200
      depends_on:
        - backend-rest
      networks:
        - frontend

networks:
  backend:
  frontend:
