version: '3.7'
services:
  backend:
    build: 
      context: ./backend
    volumes: 
      - ./backend:/flask
    ports: 
      - 5000:5000
    networks:
      - backend
      - frontend

  frontend:
      build:
        context: ./frontend
      volumes: 
        - ./frontend/src:/angular/src
        - ./frontend/package.json:/angular/package.json
        - ./frontend/package-lock.json:/angular/package-lock.json
      command: npm run dev
      ports:
        - 4200:4200
      depends_on:
        - backend
      networks:
        - frontend

networks:
  backend:
  frontend:
