FROM python:3.8

# add requirements.txt to the image
ADD requirements.txt /app/requirements.txt

# set working directory to /app/
WORKDIR /app/

# setting environment variables
ENV 

RUN pip install -r requirements.txt
